<?php

/**
 * @file HtmlRenderer.php
 * @path src/Renderer/HtmlRenderer.php
 * @version 1.0.0
 * @date 2026-09-02
 * @author Walter Torres
 * @copyright Copyright 2026, Walter Torres.
 * @license Proprietary
 * @maintainer SourceSlate Team
 * @status dev
 *
 * Renders SourceSlate project documentation as a static Material Design 3 HTML site.
 */

declare(strict_types=1);

namespace SourceSlate\Renderer;

use RuntimeException;
use SourceSlate\Model\ProjectDocumentation;

/**
 * Produces the initial static HTML documentation site.
 *
 * Rendering writes only beneath the configured output directory. The renderer
 * does not mutate PHP source files and escapes project-derived text before output.
 */
final class HtmlRenderer implements RendererInterface
{
    public function render(ProjectDocumentation $project, string $outputDirectory): void
    {
        if (!is_dir($outputDirectory) && !mkdir($outputDirectory, 0775, true) && !is_dir($outputDirectory)) {
            throw new RuntimeException(sprintf('Unable to create output directory: %s', $outputDirectory));
        }

        $assets = $outputDirectory . DIRECTORY_SEPARATOR . 'assets';
        if (!is_dir($assets) && !mkdir($assets, 0775, true) && !is_dir($assets)) {
            throw new RuntimeException(sprintf('Unable to create assets directory: %s', $assets));
        }

        $rows = '';
        foreach ($project->files as $file) {
            $symbols = $file->declaredSymbols === [] ? '&mdash;' : implode(', ', array_map('htmlspecialchars', $file->declaredSymbols));
            $rows .= sprintf(
                "<tr><td><code>%s</code></td><td>%s</td></tr>\n",
                htmlspecialchars($file->path, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'),
                $symbols,
            );
        }

        $html = sprintf(
            '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%1$s — SourceSlate</title><link rel="stylesheet" href="assets/material.css"></head><body><header><div><strong>SourceSlate</strong><span>%1$s</span></div><input type="search" id="search" placeholder="Search files or symbols" aria-label="Search documentation"></header><main><aside><nav><a href="index.html" aria-current="page">Overview</a><a href="#files">Files</a><a href="#symbols">Symbols</a></nav></aside><article><h1>%1$s</h1><p class="lede">Generated by SourceSlate.</p><section id="files"><h2>Source files</h2><div class="table-wrap"><table><thead><tr><th>File</th><th>Declared symbols</th></tr></thead><tbody>%2$s</tbody></table></div></section></article></main><script>const q=document.getElementById("search");q.addEventListener("input",()=>{const v=q.value.toLowerCase();document.querySelectorAll("tbody tr").forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(v));});</script></body></html>',
            htmlspecialchars($project->name, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'),
            $rows,
        );

        if (file_put_contents($outputDirectory . DIRECTORY_SEPARATOR . 'index.html', $html) === false) {
            throw new RuntimeException('Unable to write generated index.html.');
        }

        $themePath = dirname(__DIR__, 2) . '/resources/theme/material.css';
        if (!copy($themePath, $assets . DIRECTORY_SEPARATOR . 'material.css')) {
            throw new RuntimeException('Unable to copy the Material Design 3 theme.');
        }
    }
}
